#!/bin/sh

# Conservative value to wait for until shutting down
RESET_PCT=90

# Set up the power_fail input pin to use gpiomon
powerfail_gpio="gpiochip4 0"
supercap_pct=0

while true; do
    # shellcheck disable=SC2086
    POWER_FAIL=$(gpioget ${powerfail_gpio})
    if [ "${POWER_FAIL}" -eq 1 ]; then
        eval "$(tsmicroctl -i)"
        echo "Supercaps at ${supercap_pct}"

        if [ "${supercap_pct}" -le ${RESET_PCT} ]; then
            # Code can be added below in order to turn off power-hungry
            # devices, or start other shutdown procedures required.
            # For example:
            # Turn off cell modem:
            #   gpioset 0 8=0
            #
            # Disable relay:
            #   gpioset 4 8=0
            #
            # The wall command can be removed if wanted.

            wall "The script ${0} has detected main power has been lost! Shutting down safely to prevent filesystem damage"

            reboot
            exit
        fi
        sleep 0.5
    else
        # shellcheck disable=SC2086
        gpiomon --num-events=1 --rising-edge ${powerfail_gpio} >/dev/null 2>&1
    fi
done
